export enum DirectorField {
  TITLE = "typeahead_input_0",
  FIRST_NAME = "first_name",
  MIDDLE_NAMES = "middle_names",
  LAST_NAME = "last_name",
  PREVIOUS_NAMES = "previous_names",
  PREVIOUS_NAMES_RADIO = "previous_names_radio",
  OCCUPATION = "typeahead_input_0",
  NATIONALITY_1 = "typeahead_input_0",
  NATIONALITY_2 = "typeahead_input_1",
  NATIONALITY_3 = "typeahead_input_2",
  NATIONALITY_2_RADIO = "nationality_2_radio",
  NATIONALITY_3_RADIO = "nationality_3_radio",
  PREMISES = "premises",
  POSTCODE = "postcode",
  YES = "Yes",
  NO = "No",
  RESIDENTIAL_ADDRESS_PREMISES = "residential_address_premises",
  RESIDENTIAL_ADDRESS_ADDRESS_LINE_1 = "residential_address_line_1",
  RESIDENTIAL_ADDRESS_ADDRESS_LINE_2 = "residential_address_line_2",
  RESIDENTIAL_ADDRESS_CITY = "residential_address_city",
  RESIDENTIAL_ADDRESS_COUNTY = "residential_address_county",
  RESIDENTIAL_ADDRESS_COUNTRY = "typeahead_input_0",
  RESIDENTIAL_ADDRESS_POSTCODE = "residential_address_postcode",
}