export enum Templates {
  ACCESSIBILITY_STATEMENT = "accessibility-statement",
  ACTIVE_DIRECTORS = "active-directors",
  SIGNOUT = "signout",
  START = "start",
  SERVICE_OFFLINE_MID_JOURNEY = "service-offline-mid-journey",
  CONFIRM_COMPANY = "confirm-company",
  ERROR_404 = "page-not-found",
  STOP_PAGE = "stop-page",
  // TM01
  REMOVE_DIRECTOR = "remove-director",
  REMOVE_DIRECTOR_CHECK_ANSWERS = "remove-director-check-answers",
  REMOVE_DIRECTOR_SUBMITTED = "remove-director-submitted",
  // AP01
  DIRECTOR_NAME = "director-name",
  DIRECTOR_DATE_DETAILS = "director-date-details",
  DIRECTOR_NATIONALITY = "director-nationality",
  DIRECTOR_OCCUPATION = "director-occupation",
  DIRECTOR_CORRESPONDENCE_ADDRESS = "director-correspondence-address",
  DIRECTOR_CORRESPONDENCE_ADDRESS_SEARCH = "director-correspondence-address-search",
  DIRECTOR_CORRESPONDENCE_CHOOSE_ADDRESS = "director-correspondence-address-choose-address",
  DIRECTOR_CORRESPONDENCE_ADDRESS_MANUAL = "director-correspondence-address-manual",
  DIRECTOR_CORRESPONDENCE_ADDRESS_LINK = "director-correspondence-address-link",
  DIRECTOR_LINK_CORRESPONDENCE_ADDRESS_ENTER_MANUALLY = "director-link-correspondence-address-enter-manually",
  DIRECTOR_CONFIRM_CORRESPONDENCE_ADDRESS = "director-confirm-correspondence-address",
  DIRECTOR_CONFIRM_RESIDENTIAL_ADDRESS = "director-confirm-residential-address",
  DIRECTOR_RESIDENTIAL_ADDRESS = "director-residential-address",
  DIRECTOR_RESIDENTIAL_ADDRESS_SEARCH = "director-residential-address-search",
  DIRECTOR_RESIDENTIAL_CHOOSE_ADDRESS = "director-residential-address-search-choose-address",
  DIRECTOR_RESIDENTIAL_ADDRESS_MANUAL = "director-residential-address-manual",
  DIRECTOR_RESIDENTIAL_ADDRESS_LINK = "director-residential-address-link",
  DIRECTOR_PROTECTED_DETAILS = "director-protected-details",
  APPOINT_DIRECTOR_CHECK_ANSWERS = "appoint-director-check-answers",
  APPOINT_DIRECTOR_SUBMITTED = "appoint-director-submitted",
  // CH01
  UPDATE_DIRECTOR_DETAILS = "update/update-director-details",
  UPDATE_DIRECTOR_NAME = "update/update-director-name",
  DIRECTOR_DATE_OF_CHANGE = "update/director-date-of-change",
  UPDATE_DIRECTOR_CHECK_ANSWERS = "update/update-director-check-answers",
  UPDATE_DIRECTOR_OCCUPATION = "update/update-director-occupation",
  UPDATE_DIRECTOR_SUBMITTED = "update/update-director-submitted",
  UPDATE_DIRECTOR_NATIONALITY = "update/update-director-nationailty",
}